// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/SearchRequest.proto

package com.hongguo.netty.proto;

public final class SearchRequest {
  private SearchRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AdvertisementSearchRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:search.AdvertisementSearchRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string query = 1;</code>
     */
    boolean hasQuery();
    /**
     * <code>optional string query = 1;</code>
     */
    java.lang.String getQuery();
    /**
     * <code>optional string query = 1;</code>
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    /**
     * <code>optional int32 page_num = 2 [default = 1];</code>
     */
    boolean hasPageNum();
    /**
     * <code>optional int32 page_num = 2 [default = 1];</code>
     */
    int getPageNum();

    /**
     * <code>optional int32 page_size = 3 [default = 10];</code>
     */
    boolean hasPageSize();
    /**
     * <code>optional int32 page_size = 3 [default = 10];</code>
     */
    int getPageSize();
  }
  /**
   * Protobuf type {@code search.AdvertisementSearchRequest}
   */
  public  static final class AdvertisementSearchRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:search.AdvertisementSearchRequest)
      AdvertisementSearchRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdvertisementSearchRequest.newBuilder() to construct.
    private AdvertisementSearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdvertisementSearchRequest() {
      query_ = "";
      pageNum_ = 1;
      pageSize_ = 10;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AdvertisementSearchRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              query_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pageNum_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              pageSize_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hongguo.netty.proto.SearchRequest.internal_static_search_AdvertisementSearchRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hongguo.netty.proto.SearchRequest.internal_static_search_AdvertisementSearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest.class, com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest.Builder.class);
    }

    private int bitField0_;
    public static final int QUERY_FIELD_NUMBER = 1;
    private volatile java.lang.Object query_;
    /**
     * <code>optional string query = 1;</code>
     */
    public boolean hasQuery() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string query = 1;</code>
     */
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          query_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string query = 1;</code>
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGE_NUM_FIELD_NUMBER = 2;
    private int pageNum_;
    /**
     * <code>optional int32 page_num = 2 [default = 1];</code>
     */
    public boolean hasPageNum() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 page_num = 2 [default = 1];</code>
     */
    public int getPageNum() {
      return pageNum_;
    }

    public static final int PAGE_SIZE_FIELD_NUMBER = 3;
    private int pageSize_;
    /**
     * <code>optional int32 page_size = 3 [default = 10];</code>
     */
    public boolean hasPageSize() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 page_size = 3 [default = 10];</code>
     */
    public int getPageSize() {
      return pageSize_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, query_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, pageNum_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, pageSize_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, query_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageNum_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pageSize_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest)) {
        return super.equals(obj);
      }
      com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest other = (com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest) obj;

      if (hasQuery() != other.hasQuery()) return false;
      if (hasQuery()) {
        if (!getQuery()
            .equals(other.getQuery())) return false;
      }
      if (hasPageNum() != other.hasPageNum()) return false;
      if (hasPageNum()) {
        if (getPageNum()
            != other.getPageNum()) return false;
      }
      if (hasPageSize() != other.hasPageSize()) return false;
      if (hasPageSize()) {
        if (getPageSize()
            != other.getPageSize()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasQuery()) {
        hash = (37 * hash) + QUERY_FIELD_NUMBER;
        hash = (53 * hash) + getQuery().hashCode();
      }
      if (hasPageNum()) {
        hash = (37 * hash) + PAGE_NUM_FIELD_NUMBER;
        hash = (53 * hash) + getPageNum();
      }
      if (hasPageSize()) {
        hash = (37 * hash) + PAGE_SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getPageSize();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code search.AdvertisementSearchRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:search.AdvertisementSearchRequest)
        com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hongguo.netty.proto.SearchRequest.internal_static_search_AdvertisementSearchRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hongguo.netty.proto.SearchRequest.internal_static_search_AdvertisementSearchRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest.class, com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest.Builder.class);
      }

      // Construct using com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        query_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        pageNum_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        pageSize_ = 10;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hongguo.netty.proto.SearchRequest.internal_static_search_AdvertisementSearchRequest_descriptor;
      }

      @java.lang.Override
      public com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest getDefaultInstanceForType() {
        return com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest build() {
        com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest buildPartial() {
        com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest result = new com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.query_ = query_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pageNum_ = pageNum_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pageSize_ = pageSize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest) {
          return mergeFrom((com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest other) {
        if (other == com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest.getDefaultInstance()) return this;
        if (other.hasQuery()) {
          bitField0_ |= 0x00000001;
          query_ = other.query_;
          onChanged();
        }
        if (other.hasPageNum()) {
          setPageNum(other.getPageNum());
        }
        if (other.hasPageSize()) {
          setPageSize(other.getPageSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object query_ = "";
      /**
       * <code>optional string query = 1;</code>
       */
      public boolean hasQuery() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string query = 1;</code>
       */
      public java.lang.String getQuery() {
        java.lang.Object ref = query_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            query_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string query = 1;</code>
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        java.lang.Object ref = query_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          query_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string query = 1;</code>
       */
      public Builder setQuery(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string query = 1;</code>
       */
      public Builder clearQuery() {
        bitField0_ = (bitField0_ & ~0x00000001);
        query_ = getDefaultInstance().getQuery();
        onChanged();
        return this;
      }
      /**
       * <code>optional string query = 1;</code>
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        query_ = value;
        onChanged();
        return this;
      }

      private int pageNum_ = 1;
      /**
       * <code>optional int32 page_num = 2 [default = 1];</code>
       */
      public boolean hasPageNum() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 page_num = 2 [default = 1];</code>
       */
      public int getPageNum() {
        return pageNum_;
      }
      /**
       * <code>optional int32 page_num = 2 [default = 1];</code>
       */
      public Builder setPageNum(int value) {
        bitField0_ |= 0x00000002;
        pageNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 page_num = 2 [default = 1];</code>
       */
      public Builder clearPageNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pageNum_ = 1;
        onChanged();
        return this;
      }

      private int pageSize_ = 10;
      /**
       * <code>optional int32 page_size = 3 [default = 10];</code>
       */
      public boolean hasPageSize() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 page_size = 3 [default = 10];</code>
       */
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <code>optional int32 page_size = 3 [default = 10];</code>
       */
      public Builder setPageSize(int value) {
        bitField0_ |= 0x00000004;
        pageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 page_size = 3 [default = 10];</code>
       */
      public Builder clearPageSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pageSize_ = 10;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:search.AdvertisementSearchRequest)
    }

    // @@protoc_insertion_point(class_scope:search.AdvertisementSearchRequest)
    private static final com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest();
    }

    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AdvertisementSearchRequest>
        PARSER = new com.google.protobuf.AbstractParser<AdvertisementSearchRequest>() {
      @java.lang.Override
      public AdvertisementSearchRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdvertisementSearchRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdvertisementSearchRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdvertisementSearchRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hongguo.netty.proto.SearchRequest.AdvertisementSearchRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AdvertisementSearchResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:search.AdvertisementSearchResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>optional string result = 1;</code>
     */
    java.lang.String getResult();
    /**
     * <code>optional string result = 1;</code>
     */
    com.google.protobuf.ByteString
        getResultBytes();

    /**
     * <code>optional int32 page_num = 2;</code>
     */
    boolean hasPageNum();
    /**
     * <code>optional int32 page_num = 2;</code>
     */
    int getPageNum();

    /**
     * <code>optional int32 page_size = 3;</code>
     */
    boolean hasPageSize();
    /**
     * <code>optional int32 page_size = 3;</code>
     */
    int getPageSize();
  }
  /**
   * Protobuf type {@code search.AdvertisementSearchResponse}
   */
  public  static final class AdvertisementSearchResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:search.AdvertisementSearchResponse)
      AdvertisementSearchResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdvertisementSearchResponse.newBuilder() to construct.
    private AdvertisementSearchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdvertisementSearchResponse() {
      result_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AdvertisementSearchResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              result_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pageNum_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              pageSize_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hongguo.netty.proto.SearchRequest.internal_static_search_AdvertisementSearchResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hongguo.netty.proto.SearchRequest.internal_static_search_AdvertisementSearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse.class, com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse.Builder.class);
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private volatile java.lang.Object result_;
    /**
     * <code>optional string result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string result = 1;</code>
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          result_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string result = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGE_NUM_FIELD_NUMBER = 2;
    private int pageNum_;
    /**
     * <code>optional int32 page_num = 2;</code>
     */
    public boolean hasPageNum() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 page_num = 2;</code>
     */
    public int getPageNum() {
      return pageNum_;
    }

    public static final int PAGE_SIZE_FIELD_NUMBER = 3;
    private int pageSize_;
    /**
     * <code>optional int32 page_size = 3;</code>
     */
    public boolean hasPageSize() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 page_size = 3;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, result_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, pageNum_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, pageSize_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, result_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageNum_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pageSize_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse)) {
        return super.equals(obj);
      }
      com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse other = (com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse) obj;

      if (hasResult() != other.hasResult()) return false;
      if (hasResult()) {
        if (!getResult()
            .equals(other.getResult())) return false;
      }
      if (hasPageNum() != other.hasPageNum()) return false;
      if (hasPageNum()) {
        if (getPageNum()
            != other.getPageNum()) return false;
      }
      if (hasPageSize() != other.hasPageSize()) return false;
      if (hasPageSize()) {
        if (getPageSize()
            != other.getPageSize()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResult()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResult().hashCode();
      }
      if (hasPageNum()) {
        hash = (37 * hash) + PAGE_NUM_FIELD_NUMBER;
        hash = (53 * hash) + getPageNum();
      }
      if (hasPageSize()) {
        hash = (37 * hash) + PAGE_SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getPageSize();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code search.AdvertisementSearchResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:search.AdvertisementSearchResponse)
        com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hongguo.netty.proto.SearchRequest.internal_static_search_AdvertisementSearchResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hongguo.netty.proto.SearchRequest.internal_static_search_AdvertisementSearchResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse.class, com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse.Builder.class);
      }

      // Construct using com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        pageNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pageSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hongguo.netty.proto.SearchRequest.internal_static_search_AdvertisementSearchResponse_descriptor;
      }

      @java.lang.Override
      public com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse getDefaultInstanceForType() {
        return com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse build() {
        com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse buildPartial() {
        com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse result = new com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.pageNum_ = pageNum_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.pageSize_ = pageSize_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse) {
          return mergeFrom((com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse other) {
        if (other == com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse.getDefaultInstance()) return this;
        if (other.hasResult()) {
          bitField0_ |= 0x00000001;
          result_ = other.result_;
          onChanged();
        }
        if (other.hasPageNum()) {
          setPageNum(other.getPageNum());
        }
        if (other.hasPageSize()) {
          setPageSize(other.getPageSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object result_ = "";
      /**
       * <code>optional string result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string result = 1;</code>
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            result_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string result = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string result = 1;</code>
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      /**
       * <code>optional string result = 1;</code>
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }

      private int pageNum_ ;
      /**
       * <code>optional int32 page_num = 2;</code>
       */
      public boolean hasPageNum() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 page_num = 2;</code>
       */
      public int getPageNum() {
        return pageNum_;
      }
      /**
       * <code>optional int32 page_num = 2;</code>
       */
      public Builder setPageNum(int value) {
        bitField0_ |= 0x00000002;
        pageNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 page_num = 2;</code>
       */
      public Builder clearPageNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pageNum_ = 0;
        onChanged();
        return this;
      }

      private int pageSize_ ;
      /**
       * <code>optional int32 page_size = 3;</code>
       */
      public boolean hasPageSize() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 page_size = 3;</code>
       */
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <code>optional int32 page_size = 3;</code>
       */
      public Builder setPageSize(int value) {
        bitField0_ |= 0x00000004;
        pageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 page_size = 3;</code>
       */
      public Builder clearPageSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pageSize_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:search.AdvertisementSearchResponse)
    }

    // @@protoc_insertion_point(class_scope:search.AdvertisementSearchResponse)
    private static final com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse();
    }

    public static com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AdvertisementSearchResponse>
        PARSER = new com.google.protobuf.AbstractParser<AdvertisementSearchResponse>() {
      @java.lang.Override
      public AdvertisementSearchResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdvertisementSearchResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdvertisementSearchResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdvertisementSearchResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hongguo.netty.proto.SearchRequest.AdvertisementSearchResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_search_AdvertisementSearchRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_search_AdvertisementSearchRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_search_AdvertisementSearchResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_search_AdvertisementSearchResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/protobuf/SearchRequest.proto\022\006sear" +
      "ch\"W\n\032AdvertisementSearchRequest\022\r\n\005quer" +
      "y\030\001 \001(\t\022\023\n\010page_num\030\002 \001(\005:\0011\022\025\n\tpage_siz" +
      "e\030\003 \001(\005:\00210\"R\n\033AdvertisementSearchRespon" +
      "se\022\016\n\006result\030\001 \001(\t\022\020\n\010page_num\030\002 \001(\005\022\021\n\t" +
      "page_size\030\003 \001(\005B(\n\027com.hongguo.netty.pro" +
      "toB\rSearchRequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_search_AdvertisementSearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_search_AdvertisementSearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_search_AdvertisementSearchRequest_descriptor,
        new java.lang.String[] { "Query", "PageNum", "PageSize", });
    internal_static_search_AdvertisementSearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_search_AdvertisementSearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_search_AdvertisementSearchResponse_descriptor,
        new java.lang.String[] { "Result", "PageNum", "PageSize", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
